spring:
  application:
    name: springboot01
   #freemarker配置
  freemarker:
#    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

hschefu: c13abb17def941ceb90ed188779268
